---

- hosts: localhost
  user: jenk1
  become: true
  vars_prompt:
    - name: username
      prompt: Enter username for acess in NGINX
      private: no
    - name: passwd
      prompt: Wait a password for NGINX user
  roles:
    - docker-role
    - nginx-role    
